//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © 13. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("Creuna")]
[assembly: System.Reflection.AssemblyVersion("0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.13120.26")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.1Beta")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "Copyright © 13. All rights reserved.";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyCompany = "Creuna";
    
    internal const string AssemblyVersion = "0.1";
    
    internal const string AssemblyFileVersion = "0.1.13120.26";
    
    internal const string AssemblyInformationalVersion = "0.1Beta";
    
    private ThisAssembly() {
    }
}
