//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © . All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("Creuna")]
[assembly: System.Reflection.AssemblyVersion("1.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1.6")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0Patch 1")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "Copyright © . All rights reserved.";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyCompany = "Creuna";
    
    internal const string AssemblyVersion = "1.0.1";
    
    internal const string AssemblyFileVersion = "1.0.1.6";
    
    internal const string AssemblyInformationalVersion = "1.0Patch 1";
    
    private ThisAssembly() {
    }
}
